### ISSUE TITLE
URL https://artifactory.pictet.io not reacheable

### ISSUE THREAD

**Issue by IOhacker** [pictet-technologies-open-source/reactive-todo-list-r2dbc#2]
Hello,

I got the following error when trying to build the todo-list-ui project:

npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://artifactory.pictet.io/artifactory/api/npm/npm/zone.js/-/zone.js-0.10.3.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.pictet.io
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:

**Comment by alexandre-jacquot-ptl** [comment]
Fixed. I have recreated the package-lock.json file to reference a public registry instead of our private one.
